"use strict";

const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const {DatabaseSync}=require("node:sqlite");

function iso(){return new Date().toISOString()}
function keyForFile(file){return path.basename(file).replace(/\.json$/i,"").replace(/\.jsonl$/i,"")}
function ensureParent(file){fs.mkdirSync(path.dirname(file),{recursive:true})}
function parseJson(value,fallback={}){try{return JSON.parse(value)}catch{return fallback}}
function bool(v){return v?1:0}
function targetDomain(action){const a=String(action||"").toLowerCase();if(a.startsWith("govee.")||a.startsWith("lighting."))return "lighting";if(a==="tv.power"||a.startsWith("display.")||a.startsWith("av."))return "display";return "other"}

const NORMALIZED_NAMESPACES=new Set(["devices","hardware","automations","class-schedules","scheduler-calendar","scenes","sessions"]);

class ClassroomHubStorage{
  constructor({dataDir,dbFile,masterKeyFile,legacyMirror=false}){
    this.dataDir=path.resolve(dataDir);
    this.dbFile=path.resolve(dbFile||path.join(this.dataDir,"classroom-control-hub.db"));
    this.masterKeyFile=masterKeyFile||"/run/secrets/classroom-control-hub-master-key";
    this.legacyMirror=!!legacyMirror;
    ensureParent(this.dbFile);
    this.db=new DatabaseSync(this.dbFile);
    this.db.exec(`
      PRAGMA journal_mode=WAL;
      PRAGMA synchronous=NORMAL;
      PRAGMA foreign_keys=ON;
      CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,applied_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS object_store(namespace TEXT PRIMARY KEY,value_json TEXT NOT NULL,source_file TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT NOT NULL,kind TEXT,payload_json TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS idx_audit_events_at ON audit_events(at DESC);
      CREATE INDEX IF NOT EXISTS idx_audit_events_kind ON audit_events(kind,at DESC);
      CREATE TABLE IF NOT EXISTS telemetry_state(key TEXT PRIMARY KEY,kind TEXT NOT NULL,payload_json TEXT NOT NULL DEFAULT '{}',first_seen TEXT NOT NULL,last_seen TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 1);
      CREATE INDEX IF NOT EXISTS idx_telemetry_state_kind ON telemetry_state(kind,last_seen DESC);
      CREATE TABLE IF NOT EXISTS secret_store(name TEXT PRIMARY KEY,cipher_text TEXT NOT NULL,iv TEXT NOT NULL,auth_tag TEXT NOT NULL,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS certificates(name TEXT PRIMARY KEY,certificate_pem TEXT NOT NULL,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS migration_history(id INTEGER PRIMARY KEY AUTOINCREMENT,source TEXT NOT NULL,target TEXT NOT NULL,records INTEGER NOT NULL DEFAULT 0,details_json TEXT NOT NULL DEFAULT '{}',migrated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS site_settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS display_devices(id TEXT PRIMARY KEY,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS device_groups(domain TEXT NOT NULL,name TEXT NOT NULL,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL,PRIMARY KEY(domain,name));
      CREATE TABLE IF NOT EXISTS device_group_members(domain TEXT NOT NULL,group_name TEXT NOT NULL,member_id TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(domain,group_name,member_id),FOREIGN KEY(domain,group_name) REFERENCES device_groups(domain,name) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS integrations(id TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 1,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS managed_modules(id TEXT PRIMARY KEY,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS integration_devices(integration_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL,PRIMARY KEY(integration_id,id),FOREIGN KEY(integration_id) REFERENCES integrations(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS class_schedules(id TEXT PRIMARY KEY,name TEXT NOT NULL,start_time TEXT,end_time TEXT,enabled INTEGER NOT NULL DEFAULT 1,data_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS scheduler_calendar(id INTEGER PRIMARY KEY CHECK(id=1),skip_federal_holidays INTEGER NOT NULL DEFAULT 1,excluded_dates_json TEXT NOT NULL DEFAULT '[]',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS automations(id TEXT PRIMARY KEY,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,action TEXT,schedule_mode TEXT,data_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS automation_actions(id TEXT PRIMARY KEY,automation_id TEXT NOT NULL,position INTEGER NOT NULL,action TEXT NOT NULL,target_domain TEXT NOT NULL,use_event_targets INTEGER NOT NULL DEFAULT 0,delay_seconds INTEGER NOT NULL DEFAULT 0,continue_on_error INTEGER NOT NULL DEFAULT 1,payload_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(automation_id) REFERENCES automations(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_automation_actions_parent ON automation_actions(automation_id,position);
      CREATE TABLE IF NOT EXISTS automation_targets(action_id TEXT NOT NULL,target_id TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(action_id,target_id),FOREIGN KEY(action_id) REFERENCES automation_actions(id) ON DELETE CASCADE);
      CREATE TABLE IF NOT EXISTS scenes(id TEXT PRIMARY KEY,name TEXT,data_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,data_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS access_profiles(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'viewer',enabled INTEGER NOT NULL DEFAULT 1,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS system_preferences(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE COLLATE NOCASE,display_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'viewer',password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_login_at TEXT);
      CREATE TABLE IF NOT EXISTS user_sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,remote_addr TEXT,user_agent TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
      CREATE INDEX IF NOT EXISTS idx_user_sessions_expiry ON user_sessions(expires_at);
    `);
    this.db.prepare("INSERT OR IGNORE INTO schema_migrations(version,name,applied_at) VALUES(1,'initial sqlite storage',?)").run(iso());
    this._loadMasterKey();
  }

  _loadMasterKey(){
    try{const raw=fs.readFileSync(this.masterKeyFile);this.masterKey=raw.length===32?raw:crypto.createHash("sha256").update(raw).digest()}catch{this.masterKey=null}
  }

  // Generic object store keeps compatibility with JSON-backed namespaces that have not yet been fully normalized.
  get(namespace,fallback=null){const row=this.db.prepare("SELECT value_json FROM object_store WHERE namespace=?").get(String(namespace));return row?parseJson(row.value_json,fallback):fallback}
  put(namespace,value,sourceFile=null){const now=iso();this.db.prepare(`INSERT INTO object_store(namespace,value_json,source_file,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(namespace) DO UPDATE SET value_json=excluded.value_json,source_file=excluded.source_file,updated_at=excluded.updated_at`).run(String(namespace),JSON.stringify(value),sourceFile,now,now);return value}
  delete(namespace){this.db.prepare("DELETE FROM object_store WHERE namespace=?").run(String(namespace))}
  recordAudit(kind,payload={}){this.db.prepare("INSERT INTO audit_events(at,kind,payload_json) VALUES(?,?,?)").run(iso(),String(kind||"event"),JSON.stringify(payload||{}))}
  recentAudit(limit=100,kind=null){const n=Math.max(1,Math.min(1000,Number(limit)||100));const rows=kind?this.db.prepare("SELECT * FROM audit_events WHERE kind=? ORDER BY id DESC LIMIT ?").all(String(kind),n):this.db.prepare("SELECT * FROM audit_events ORDER BY id DESC LIMIT ?").all(n);return rows.map(r=>({id:r.id,at:r.at,kind:r.kind,payload:parseJson(r.payload_json,{})}))}
  upsertTelemetry(key,kind,payload={}){const now=iso();this.db.prepare(`INSERT INTO telemetry_state(key,kind,payload_json,first_seen,last_seen,count) VALUES(?,?,?,?,?,1) ON CONFLICT(key) DO UPDATE SET kind=excluded.kind,payload_json=excluded.payload_json,last_seen=excluded.last_seen,count=telemetry_state.count+1`).run(String(key),String(kind),JSON.stringify(payload||{}),now,now)}
  telemetry(kind=null,limit=500){const n=Math.max(1,Math.min(5000,Number(limit)||500));const rows=kind?this.db.prepare("SELECT * FROM telemetry_state WHERE kind=? ORDER BY last_seen DESC LIMIT ?").all(String(kind),n):this.db.prepare("SELECT * FROM telemetry_state ORDER BY last_seen DESC LIMIT ?").all(n);return rows.map(r=>({key:r.key,kind:r.kind,payload:parseJson(r.payload_json,{}),firstSeen:r.first_seen,lastSeen:r.last_seen,count:r.count}))}

  // --- Normalized domain adapters ---
  listDisplays(){return this.db.prepare("SELECT * FROM display_devices ORDER BY id").all().map(r=>({id:r.id,name:r.name,enabled:!!r.enabled,...parseJson(r.config_json,{})}))}
  putDisplay(d){const now=iso(),id=String(d.id),name=String(d.name||id),cfg={...d};delete cfg.id;delete cfg.name;delete cfg.enabled;this.db.prepare(`INSERT INTO display_devices(id,name,enabled,config_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,enabled=excluded.enabled,config_json=excluded.config_json,updated_at=excluded.updated_at`).run(id,name,bool(d.enabled!==false),JSON.stringify(cfg),now)}
  listGroups(domain){return this.db.prepare("SELECT * FROM device_groups WHERE domain=? ORDER BY name").all(String(domain)).map(r=>({name:r.name,...parseJson(r.config_json,{}),members:this.db.prepare("SELECT member_id FROM device_group_members WHERE domain=? AND group_name=? ORDER BY position").all(String(domain),r.name).map(x=>x.member_id)}))}
  putGroup(domain,g){const now=iso(),name=String(g.name),cfg={...g};delete cfg.name;delete cfg.members;const tx=this.db.transaction(()=>{this.db.prepare(`INSERT INTO device_groups(domain,name,config_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(domain,name) DO UPDATE SET config_json=excluded.config_json,updated_at=excluded.updated_at`).run(domain,name,JSON.stringify(cfg),now);this.db.prepare("DELETE FROM device_group_members WHERE domain=? AND group_name=?").run(domain,name);(Array.isArray(g.members)?g.members:[]).forEach((m,i)=>this.db.prepare("INSERT INTO device_group_members(domain,group_name,member_id,position) VALUES(?,?,?,?)").run(domain,name,String(m),i))});tx()}
  listIntegrations(){return this.db.prepare("SELECT * FROM integrations ORDER BY id").all().map(r=>({id:r.id,enabled:!!r.enabled,...parseJson(r.config_json,{})}))}
  putIntegration(i){const now=iso(),id=String(i.id),cfg={...i};delete cfg.id;delete cfg.enabled;this.db.prepare(`INSERT INTO integrations(id,enabled,config_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET enabled=excluded.enabled,config_json=excluded.config_json,updated_at=excluded.updated_at`).run(id,bool(i.enabled!==false),JSON.stringify(cfg),now)}
  listManagedModules(){return this.db.prepare("SELECT * FROM managed_modules ORDER BY id").all().map(r=>({id:r.id,...parseJson(r.config_json,{})}))}
  putManagedModule(m){const now=iso(),id=String(m.id),cfg={...m};delete cfg.id;this.db.prepare(`INSERT INTO managed_modules(id,config_json,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET config_json=excluded.config_json,updated_at=excluded.updated_at`).run(id,JSON.stringify(cfg),now)}
  listIntegrationDevices(integrationId){return this.db.prepare("SELECT * FROM integration_devices WHERE integration_id=? ORDER BY id").all(String(integrationId)).map(r=>({id:r.id,name:r.name,...parseJson(r.config_json,{})}))}
  putIntegrationDevice(integrationId,d){const now=iso(),id=String(d.id),cfg={...d};delete cfg.id;delete cfg.name;this.db.prepare(`INSERT INTO integration_devices(integration_id,id,name,config_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(integration_id,id) DO UPDATE SET name=excluded.name,config_json=excluded.config_json,updated_at=excluded.updated_at`).run(String(integrationId),id,d.name||id,JSON.stringify(cfg),now)}
  listClassSchedules(){return this.db.prepare("SELECT * FROM class_schedules ORDER BY start_time,id").all().map(r=>({id:r.id,name:r.name,startTime:r.start_time,endTime:r.end_time,enabled:!!r.enabled,...parseJson(r.data_json,{})}))}
  putClassSchedule(c){const now=iso(),id=String(c.id),data={...c};delete data.id;delete data.name;delete data.startTime;delete data.endTime;delete data.enabled;this.db.prepare(`INSERT INTO class_schedules(id,name,start_time,end_time,enabled,data_json,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,start_time=excluded.start_time,end_time=excluded.end_time,enabled=excluded.enabled,data_json=excluded.data_json,updated_at=excluded.updated_at`).run(id,c.name||id,c.startTime||null,c.endTime||null,bool(c.enabled!==false),JSON.stringify(data),now)}
  deleteClassSchedule(id){this.db.prepare("DELETE FROM class_schedules WHERE id=?").run(String(id))}
  getCalendar(){const r=this.db.prepare("SELECT * FROM scheduler_calendar WHERE id=1").get();return r?{skipFederalHolidays:!!r.skip_federal_holidays,excludedDates:parseJson(r.excluded_dates_json,[])}:{skipFederalHolidays:true,excludedDates:[]}}
  putCalendar(c){this.db.prepare(`INSERT INTO scheduler_calendar(id,skip_federal_holidays,excluded_dates_json,updated_at) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET skip_federal_holidays=excluded.skip_federal_holidays,excluded_dates_json=excluded.excluded_dates_json,updated_at=excluded.updated_at`).run(bool(c?.skipFederalHolidays!==false),JSON.stringify(c?.excludedDates||[]),iso())}
  listAutomations(){const rows=this.db.prepare("SELECT * FROM automations ORDER BY name,id").all();return rows.map(r=>{const base={id:r.id,name:r.name,enabled:!!r.enabled,action:r.action,scheduleMode:r.schedule_mode,...parseJson(r.data_json,{})};base.actions=this.listAutomationActions(r.id);return base})}
  putAutomation(a){const now=iso(),id=String(a.id),data={...a};delete data.id;delete data.name;delete data.enabled;delete data.action;delete data.scheduleMode;delete data.actions;const tx=this.db.transaction(()=>{this.db.prepare(`INSERT INTO automations(id,name,enabled,action,schedule_mode,data_json,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,enabled=excluded.enabled,action=excluded.action,schedule_mode=excluded.schedule_mode,data_json=excluded.data_json,updated_at=excluded.updated_at`).run(id,a.name||id,bool(a.enabled!==false),a.action||null,a.scheduleMode||null,JSON.stringify(data),now);if(Array.isArray(a.actions))this.replaceAutomationActions(id,a.actions)});tx()}
  deleteAutomation(id){this.db.prepare("DELETE FROM automations WHERE id=?").run(String(id))}
  listAutomationActions(automationId){return this.db.prepare("SELECT * FROM automation_actions WHERE automation_id=? ORDER BY position,id").all(String(automationId)).map(r=>({id:r.id,action:r.action,targetDomain:r.target_domain,useEventTargets:!!r.use_event_targets,delaySeconds:r.delay_seconds,continueOnError:!!r.continue_on_error,targets:this.db.prepare("SELECT target_id FROM automation_targets WHERE action_id=? ORDER BY position").all(r.id).map(x=>x.target_id),...parseJson(r.payload_json,{})}))}
  replaceAutomationActions(automationId,actions){this.db.prepare("DELETE FROM automation_actions WHERE automation_id=?").run(String(automationId));actions.forEach((a,i)=>{const id=String(a.id||crypto.randomUUID()),domain=a.targetDomain||targetDomain(a.action),payload={...a};delete payload.id;delete payload.action;delete payload.targetDomain;delete payload.targets;delete payload.useEventTargets;delete payload.delaySeconds;delete payload.continueOnError;this.db.prepare("INSERT INTO automation_actions(id,automation_id,position,action,target_domain,use_event_targets,delay_seconds,continue_on_error,payload_json) VALUES(?,?,?,?,?,?,?,?,?)").run(id,String(automationId),i,String(a.action||""),domain,bool(a.useEventTargets),Math.max(0,Number(a.delaySeconds)||0),bool(a.continueOnError!==false),JSON.stringify(payload));(Array.isArray(a.targets)?a.targets:[]).forEach((t,p)=>this.db.prepare("INSERT INTO automation_targets(action_id,target_id,position) VALUES(?,?,?)").run(id,String(t),p))})}
  listScenes(){return this.db.prepare("SELECT * FROM scenes ORDER BY name,id").all().map(r=>({id:r.id,name:r.name,...parseJson(r.data_json,{})}))}
  putScene(s){const now=iso(),id=String(s.id),data={...s};delete data.id;delete data.name;this.db.prepare(`INSERT INTO scenes(id,name,data_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,data_json=excluded.data_json,updated_at=excluded.updated_at`).run(id,s.name||id,JSON.stringify(data),now)}
  listSessions(){return this.db.prepare("SELECT * FROM sessions ORDER BY id").all().map(r=>({id:r.id,...parseJson(r.data_json,{})}))}
  putSession(s){const now=iso(),id=String(s.id),data={...s};delete data.id;this.db.prepare(`INSERT INTO sessions(id,data_json,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at`).run(id,JSON.stringify(data),now)}

  // --- App preferences / access ---
  getPreference(key,fallback=null){const r=this.db.prepare("SELECT value_json FROM system_preferences WHERE key=?").get(String(key));return r?parseJson(r.value_json,fallback):fallback}
  setPreference(key,value){this.db.prepare(`INSERT INTO system_preferences(key,value_json,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).run(String(key),JSON.stringify(value),iso());return value}
  listAccessProfiles(){return this.db.prepare("SELECT * FROM access_profiles ORDER BY name,id").all().map(r=>({id:r.id,name:r.name,role:r.role,enabled:!!r.enabled,...parseJson(r.config_json,{})}))}
  putAccessProfile(p){const now=iso(),id=String(p.id||crypto.randomUUID()),cfg={...p};delete cfg.id;delete cfg.name;delete cfg.role;delete cfg.enabled;this.db.prepare(`INSERT INTO access_profiles(id,name,role,enabled,config_json,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,enabled=excluded.enabled,config_json=excluded.config_json,updated_at=excluded.updated_at`).run(id,p.name||id,p.role||"viewer",bool(p.enabled!==false),JSON.stringify(cfg),now);return {id,...p}}
  authPolicy(){return {standardHours:Math.max(1,Number(this.getPreference("auth.session.standardHours",24))||24),rememberHours:Math.max(1,Number(this.getPreference("auth.session.rememberHours",24*30))||24*30),maxSessions:Math.max(1,Number(this.getPreference("auth.session.maxSessions",10))||10)}}
  setAuthPolicy(p={}){if(p.standardHours!==undefined)this.setPreference("auth.session.standardHours",Math.max(1,Math.min(720,Number(p.standardHours)||24)));if(p.rememberHours!==undefined)this.setPreference("auth.session.rememberHours",Math.max(1,Math.min(8760,Number(p.rememberHours)||720)));if(p.maxSessions!==undefined)this.setPreference("auth.session.maxSessions",Math.max(1,Math.min(100,Number(p.maxSessions)||10)));return this.authPolicy()}
  hashPassword(password,saltHex=null){const salt=saltHex?Buffer.from(saltHex,"hex"):crypto.randomBytes(16);const hash=crypto.scryptSync(String(password),salt,64);return {salt:salt.toString("hex"),hash:hash.toString("hex")}}
  listUsers(){return this.db.prepare("SELECT id,username,display_name,role,enabled,created_at,updated_at,last_login_at FROM users ORDER BY username COLLATE NOCASE").all().map(r=>({id:r.id,username:r.username,displayName:r.display_name,role:r.role,enabled:!!r.enabled,createdAt:r.created_at,updatedAt:r.updated_at,lastLoginAt:r.last_login_at}))}
  putUser(value,{password=null}={}){const now=iso(),id=String(value.id||crypto.randomUUID()),username=String(value.username||"").trim(),displayName=String(value.displayName||value.name||username).trim(),role=String(value.role||"viewer");if(!username)throw Error("Username is required");const existing=this.db.prepare("SELECT * FROM users WHERE id=?").get(id);let salt=existing?.password_salt,hash=existing?.password_hash;if(password!==null&&password!==undefined){const ph=this.hashPassword(password);salt=ph.salt;hash=ph.hash}if(!salt||!hash)throw Error("Password is required for a new user");this.db.prepare(`INSERT INTO users(id,username,display_name,role,password_salt,password_hash,enabled,created_at,updated_at,last_login_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,display_name=excluded.display_name,role=excluded.role,password_salt=excluded.password_salt,password_hash=excluded.password_hash,enabled=excluded.enabled,updated_at=excluded.updated_at`).run(id,username,displayName||username,role,salt,hash,bool(value?.enabled!==false),existing?.created_at||now,now,existing?.last_login_at||null);return this.listUsers().find(x=>x.id===id)}
  deleteUser(id){this.db.prepare("DELETE FROM users WHERE id=?").run(String(id))}
  verifyUser(username,password){const r=this.db.prepare("SELECT * FROM users WHERE username=? COLLATE NOCASE AND enabled=1").get(String(username||"").trim());if(!r)return null;const got=this.hashPassword(password,r.password_salt),a=Buffer.from(got.hash,"hex"),b=Buffer.from(r.password_hash,"hex");if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;return {id:r.id,username:r.username,displayName:r.display_name,role:r.role,enabled:!!r.enabled}}
  createSession(user,{remoteAddr="",userAgent="",ttlHours=null}={}){this.cleanupSessions();const policy=this.authPolicy(),hours=Math.max(1,Math.min(720,Number(ttlHours)||policy.standardHours)),token=crypto.randomBytes(32).toString("base64url"),hash=crypto.createHash("sha256").update(token).digest("hex"),id=crypto.randomUUID(),now=new Date(),exp=new Date(now.getTime()+hours*3600000);this.db.prepare("INSERT INTO user_sessions(id,user_id,token_hash,created_at,expires_at,last_seen_at,remote_addr,user_agent) VALUES(?,?,?,?,?,?,?,?)").run(id,user.id,hash,now.toISOString(),exp.toISOString(),now.toISOString(),String(remoteAddr||""),String(userAgent||"").slice(0,500));this.db.prepare("UPDATE users SET last_login_at=?,updated_at=? WHERE id=?").run(now.toISOString(),now.toISOString(),user.id);const sessions=this.listUserSessions(user.id);for(const extra of sessions.slice(policy.maxSessions))this.deleteUserSession(user.id,extra.id);return {token,expiresAt:exp.toISOString()}}
  sessionUser(token){if(!token)return null;this.cleanupSessions();const hash=crypto.createHash("sha256").update(String(token)).digest("hex"),r=this.db.prepare(`SELECT s.id sessionId,s.expires_at expiresAt,u.id,u.username,u.display_name displayName,u.role,u.enabled FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND u.enabled=1 AND s.expires_at>?`).get(hash,iso());if(!r)return null;this.db.prepare("UPDATE user_sessions SET last_seen_at=? WHERE id=?").run(iso(),r.sessionId);return {...r,enabled:!!r.enabled}}
  deleteSession(token){if(!token)return;const hash=crypto.createHash("sha256").update(String(token)).digest("hex");this.db.prepare("DELETE FROM user_sessions WHERE token_hash=?").run(hash)}
  listUserSessions(userId){this.cleanupSessions();return this.db.prepare("SELECT id,created_at createdAt,expires_at expiresAt,last_seen_at lastSeenAt,remote_addr remoteAddr,user_agent userAgent FROM user_sessions WHERE user_id=? ORDER BY last_seen_at DESC").all(String(userId))}
  deleteUserSession(userId,sessionId){return this.db.prepare("DELETE FROM user_sessions WHERE id=? AND user_id=?").run(String(sessionId),String(userId)).changes>0}
  deleteAllUserSessions(userId,{exceptSessionId=null}={}){if(exceptSessionId)return this.db.prepare("DELETE FROM user_sessions WHERE user_id=? AND id<>?").run(String(userId),String(exceptSessionId)).changes;return this.db.prepare("DELETE FROM user_sessions WHERE user_id=?").run(String(userId)).changes}
  listAllUserSessions(){this.cleanupSessions();return this.db.prepare(`SELECT s.id,s.user_id userId,u.username,u.display_name displayName,u.role,s.created_at createdAt,s.expires_at expiresAt,s.last_seen_at lastSeenAt,s.remote_addr remoteAddr,s.user_agent userAgent FROM user_sessions s JOIN users u ON u.id=s.user_id ORDER BY s.last_seen_at DESC`).all()}
  resetUserPassword(userId,newPassword){const user=this.listUsers().find(x=>x.id===String(userId));if(!user)throw Error("User not found");const updated=this.putUser(user,{password:newPassword});this.deleteAllUserSessions(user.id);return updated}
  verifyUserPassword(userId,password){const r=this.db.prepare("SELECT password_salt,password_hash FROM users WHERE id=? AND enabled=1").get(String(userId));if(!r)return false;const got=this.hashPassword(password,r.password_salt),a=Buffer.from(got.hash,"hex"),b=Buffer.from(r.password_hash,"hex");return a.length===b.length&&crypto.timingSafeEqual(a,b)}
  changeUserPassword(userId,currentPassword,newPassword){if(!this.verifyUserPassword(userId,currentPassword))throw Error("Current password is incorrect");const user=this.listUsers().find(x=>x.id===String(userId));if(!user)throw Error("User not found");return this.putUser(user,{password:newPassword})}
  cleanupSessions(){this.db.prepare("DELETE FROM user_sessions WHERE expires_at<=?").run(iso())}
  requireMasterKey(){if(!this.masterKey)throw Error(`Encrypted secret storage unavailable; master key not readable at ${this.masterKeyFile}`);return this.masterKey}
  putSecret(name,value,metadata={}){const key=this.requireMasterKey(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key,iv),ciphertext=Buffer.concat([cipher.update(Buffer.isBuffer(value)?value:Buffer.from(String(value),"utf8")),cipher.final()]),tag=cipher.getAuthTag(),now=iso();this.db.prepare(`INSERT INTO secret_store(name,cipher_text,iv,auth_tag,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET cipher_text=excluded.cipher_text,iv=excluded.iv,auth_tag=excluded.auth_tag,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at`).run(String(name),ciphertext.toString("base64"),iv.toString("base64"),tag.toString("base64"),JSON.stringify(metadata||{}),now,now)}
  getSecret(name,{asBuffer=false}={}){const row=this.db.prepare("SELECT * FROM secret_store WHERE name=?").get(String(name));if(!row)return null;const decipher=crypto.createDecipheriv("aes-256-gcm",this.requireMasterKey(),Buffer.from(row.iv,"base64"));decipher.setAuthTag(Buffer.from(row.auth_tag,"base64"));const plain=Buffer.concat([decipher.update(Buffer.from(row.cipher_text,"base64")),decipher.final()]);return asBuffer?plain:plain.toString("utf8")}
  hasSecret(name){return !!this.db.prepare("SELECT 1 ok FROM secret_store WHERE name=?").get(String(name))}
  listSecrets(){return this.db.prepare("SELECT name,metadata_json,created_at,updated_at FROM secret_store ORDER BY name").all().map(r=>({name:r.name,metadata:parseJson(r.metadata_json,{}),createdAt:r.created_at,updatedAt:r.updated_at}))}
  deleteSecret(name){this.db.prepare("DELETE FROM secret_store WHERE name=?").run(String(name))}
  importSecretFile(name,file,metadata={}){if(this.hasSecret(name)||!fs.existsSync(file))return false;this.putSecret(name,fs.readFileSync(file),{...metadata,importedFrom:file});this.recordMigration(file,`sqlite:secret_store/${name}`,1,{type:"encrypted-secret"});return true}

  putCertificate(name,pem,metadata={}){const now=iso();this.db.prepare(`INSERT INTO certificates(name,certificate_pem,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET certificate_pem=excluded.certificate_pem,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at`).run(String(name),String(pem),JSON.stringify(metadata||{}),now,now)}
  getCertificate(name){return this.db.prepare("SELECT certificate_pem FROM certificates WHERE name=?").get(String(name))?.certificate_pem||null}
  listCertificates(){return this.db.prepare("SELECT name,metadata_json,created_at,updated_at FROM certificates ORDER BY name").all().map(r=>({name:r.name,metadata:parseJson(r.metadata_json,{}),createdAt:r.created_at,updatedAt:r.updated_at}))}
}

module.exports={ClassroomHubStorage,keyForFile,NORMALIZED_NAMESPACES};
